# customer added 2021-01-01
# custormer name client2 (clie2)


client : {
  name : clie2,
  name_tx : client2,
  machine_type : "c2-standard-4",
  startup_script : "atm10.sh",
  zone : "us-west1-a",
  disk : {
    disk_size : 10,
    disk_type : "pd-ssd"
  },
  file_path : "mc-server2/world2.zip"
}
#custom-2-8192
#n1-standard-2
#c3-standard-4
#"zone/us-west1-a/machineTypes/c2-standard-4"
#"us-central1-a"